### ISSUE TITLE
Documentation must reference the terraform registry module

### ISSUE THREAD

**Issue by LaurentLesle** [aztfmod/terraform-azurerm-caf-frontdoor#1]
must reference the terraform registry module instead of relative path

![image](https://user-images.githubusercontent.com/4702224/75180866-e5c19e80-56f1-11ea-9e65-a4ab37f8bea7.png)

**Comment by fireblade95402** [comment]
Thanks Laurent. I'm updating and testing the change now. As I need to change the examples as well. Also, yesterday saw you need to have the features included to run the expamples. So adding that into a backend.tf file
