### ISSUE TITLE
Doesn't work with custom domain using cert from AzureKeyVault

### ISSUE THREAD

**Issue by hassant** [aztfmod/terraform-azurerm-caf-frontdoor#7]
When using a custom cert from AzureKeyVault, it's required to specify the certificate_source as per the [doc](https://www.terraform.io/docs/providers/azurerm/r/frontdoor.html#certificate_source) otherwise it defaults to FrontDoor

Even if you specify AzureKeyVault in the FrontDoor object, because of the **certificate_source** is missing at [line 85](https://github.com/aztfmod/terraform-azurerm-caf-frontdoor/blob/35d2bc2c4a6a99b119d579e0c8fa83d1d2edcc5b/module.tf#L85) the module errors out. It should be like:

```
content {
          certificate_source                         = custom_https_configuration.value.certificate_source
          azure_key_vault_certificate_vault_id       = custom_https_configuration.value.azure_key_vault_certificate_vault_id
          azure_key_vault_certificate_secret_name    = custom_https_configuration.value.azure_key_vault_certificate_secret_name
          azure_key_vault_certificate_secret_version = custom_https_configuration.value.azure_key_vault_certificate_secret_version
        }
```

**Comment by arnaudlh** [comment]
Hi @fireblade95402  do you mind please have a look? thanks!

**Comment by fireblade95402** [comment]
Thanks for pointing it out to me. I have the documentation correct, just not the module. Another reason to get the testing elements in. Just need time :) I'll update and create a PR
